Translate Generics session
AcademyIFCE/swift-book-markdown pull request #13
Opened 2019-10-09 00:55 UTC by allymf

Translate Generics session of the SwiftTour.md file

2019-10-09 20:09 UTC, trastoan requested changes

2019-10-09 20:09 UTC, trastoan commented on GuidedTour/SwiftTour.md
> +// Reimplementando do tipo opcional da biblioteca padrão da Swift
Reimplementando o tipo...

2019-10-09 20:09 UTC, trastoan commented on GuidedTour/SwiftTour.md
> +Use `where` logo antes do corpo para especificar uma lista de requisitos—por exemplo, para exigir que um tipo implemente um protocolo, para exigir que dois tipos sejam iguais, ou para exigir que uma
substituir hífen por virgula

2019-10-11 11:43 UTC, allymf commented on GuidedTour/SwiftTour.md
> +Use `where` logo antes do corpo para especificar uma lista de requisitos—por exemplo, para exigir que um tipo implemente um protocolo, para exigir que dois tipos sejam iguais, ou para exigir que uma
Just pushed the correction

2019-10-12 03:35 UTC, merged