Translate Functions and Closures Topic
AcademyIFCE/swift-book-markdown pull request #18
Opened 2019-10-09 02:38 UTC by allymf

Translation of Functions and Closures Topic from the SwiftTour.md file

#17 Solving this issue

2019-10-09 20:07 UTC, trastoan requested changes

2019-10-09 20:07 UTC, trastoan commented on GuidedTour/SwiftTour.md
> +Por padrão, funções usam os nomes dos seus parâmetros como rótulos para os seus argumentos. Escreva um rótulo de argumento customoizado antes do nome do parâmetro, ou escreva `_` para não usar um rót
Customizado

2019-10-09 20:07 UTC, trastoan commented on GuidedTour/SwiftTour.md
> +Funções são na verdade um tipo expecial de closures: blocos de código que podem ser chamados depois. O código dentro de uma closure tem acesso a coisas como variáveis e funções que estava disponíveis
especial
onde 
sem um nome ao circundar
Tem uns hífens zuados no meio do texto, deve ter sido problema na conversão pra markdown

2019-10-09 20:07 UTC, trastoan commented on GuidedTour/SwiftTour.md
> +Você tem diversas opções para escrever closures de forma mais concisa. Quando o tipo de uma closure já é conhecido, como o callback para um delegate, você pode omitir o tipo dos seus parâmetros, seu
Closures de expressão única retornam .....

2019-10-09 20:07 UTC, trastoan commented on GuidedTour/SwiftTour.md
> +Você pode se referir aos parâmteros por número ao invés do nome—essa abordagem é especialmente útil em closures muito curtas. Uma closure passada como o último argumento para uma função pode aparecer
uma virgula no local do hífen

2019-10-11 11:52 UTC, allymf commented on GuidedTour/SwiftTour.md
> +Você pode se referir aos parâmteros por número ao invés do nome—essa abordagem é especialmente útil em closures muito curtas. Uma closure passada como o último argumento para uma função pode aparecer
Just pushed the corrections

2019-10-12 03:35 UTC, merged