Languageguide/collectiontypes arrays
AcademyIFCE/swift-book-markdown pull request #205
Opened 2022-01-09 05:13 UTC by TiagoSAmaral

Finalizado tradução de Collection Types/Arrays

2022-03-31 17:31 UTC, reisdev requested changes
Propostas dessa review: 
- Correção de erros de tradução e digitação
- Adição do link para as respectivas traduções no README
- Remoção do arquivo .xcuserdata

2022-03-31 17:31 UTC, reisdev commented on LanguageGuide/CollectionTypes.md
> +Swift fornece três tipos primários de coleções, conhecidos como arrays, sets (conjuntos), e dicionários, para armazenar coleções de valores. Arrays são coleções ordenadas de valores. Sets são coleçõe
Corrigir o trecho "Sets são coleções não ordenadas _**de**_ valores únicos."

2022-03-31 17:31 UTC, reisdev commented on LanguageGuide/CollectionTypes.md
> +> Tipos Array, set e dicionário de Swift são implementados como _colleções genéricas_.; Para mais informações sobre tipos de coleções, veja [Generics](Generics.md).
Corrigir "colleções" para "coleções"

2022-03-31 17:31 UTC, reisdev commented on LanguageGuide/CollectionTypes.md
> +Se você já criou um array, um set, ou um dicionário, e o atribuiu a uma variável, a coleção que é criada será *mutável*. Isso significa que você pode alterar (ou *mudar*) a coleção depois de criá-la
Esse trecho está no presente: "Se você criar um array, um set, ou um dicionário, e o atribuir a uma variável, a coleção que é criada será mutável."

2022-03-31 17:31 UTC, reisdev commented on LanguageGuide/CollectionTypes.md
> +A notação completa do tipo do array em Swift é `Array<Element>`, onde `Element` é o tipo do valor que o array é permitido armazenar. Você pode também escrever o tipo de um array de forma abreviada us
No início, seria "A notação completa do tipo array". Logo a seguir, "`Element`é o tipo _**dos valores**_"

2022-03-31 17:31 UTC, reisdev commented on LanguageGuide/CollectionTypes.md
>  var someInts = [Int]()
Sugiro traduzir também os trechos de código, pra facilitar a compreensão para alguém que não saiba inglês

2022-03-31 17:31 UTC, reisdev commented on LanguageGuide/CollectionTypes.md
> +O tipo `Array` do Swift também fornece um inicializador para riar um array de um certo tamanho, com todos os seus valores definidos para o mesmo valor padrão. Você pode passar para este inicializador
- Corrigir "fornece um inicializador para **_criar_** um array [...]"
- Corrigir "para este inicializador o valor padrão **_do_** tipo apropriado"

2022-03-31 17:31 UTC, reisdev commented on LanguageGuide/CollectionTypes.md
> +### Criando um array por Adicionar Dois Arrays Juntos
Sugestão de melhoria: "Criando um array unindo dois arrays"

2022-03-31 17:31 UTC, reisdev commented on LanguageGuide/CollectionTypes.md
> +A variável `shoppingList` é declarada como "um array de valores string", escrito como `[String]`. Portanto este array em particular possui especificamente um valor do tipo `String`, é permitido a ele
- Corrigir "Portanto esse array em particular" para "Como especificamente esse array possui um tipo de valor String, ele só pode armazenar valores String"

2022-03-31 17:31 UTC, reisdev commented on LanguageGuide/CollectionTypes.md
> +Neste caso, o array literal contém dois valores `String`e nada mais.  Correspondendo ao tipo da declaração da variável `shoppingList` (um array que somente pode conter valores `String`), e então a at
No trecho final, corrigir "Items" para "itens"

2022-03-31 17:31 UTC, reisdev commented on LanguageGuide/CollectionTypes.md
> +Agradeça a inferencia de tipo do Swift, você não precisa escrever o tipo do array se você não está inicializando com um array literal, contendo valores do mesmo tipo. A inicialização de `shoppingList
- Corrigir "Graças à inferência de tipo em Swift, você não precisa [...]
- Corrigir "A inicialização de `shoppingList`poderia ter sido escrita de uma forma curta:"

2022-03-31 17:31 UTC, reisdev commented on LanguageGuide/CollectionTypes.md
> +Portanto, como todos os valores em um array literao são do mesmo tipo, Swift pode inferir que `[String]` [e o tipo correto para usar para a variável `shoppingList`.
Corrigir para "Como todos os valores de um array literal são de um mesmo tipo, Swift consegue inferir que [String] é o tipo correto a se usar para a variável `shoppingList`."

2022-03-31 17:31 UTC, reisdev commented on LanguageGuide/CollectionTypes.md
> +### Acessar e modificar um Array
Corrigir para "Acessando e modificando um Array"

2022-03-31 17:31 UTC, reisdev commented on LanguageGuide/CollectionTypes.md
> +Acesse e modifique um array através de seus métodos e propriedades, ou usando sintaxe subscript.
Corrigir para "Você acessa e modifica um array através de seus métodos e propriedades, ou usando a sintaxe de subscrição".

2022-03-31 17:31 UTC, reisdev commented on LanguageGuide/CollectionTypes.md
> +USe a propriedade Booleana `isEmpty` do array como um modo rápido para verificar que a propriedade `count` é igual a `0` (zero).
- Corrigir erro de digitação em "USe"
- Corrigir "para verificar _**se**_ a propriedade [...]"

2022-03-31 17:31 UTC, reisdev commented on LanguageGuide/CollectionTypes.md
> +>Se você tentar acessar ou modificar o valor em um índice que está além do limite do array, você irá disparar um erro em tempo de execução. Você pode verificar se um índice é válido antes de usá-lo c
Corrigir o "qeu" para "que"

2022-03-31 17:31 UTC, reisdev commented on LanguageGuide/CollectionTypes.md
> +// firstItem é  is now equal to "Six eggs"
Corrigir para `"firstItem agora é igual a "Six eggs"`

2022-03-31 17:31 UTC, reisdev commented on LanguageGuide/CollectionTypes.md
> +Se você quer remover o item do final de um array, use o método `removeLast()` em vez do método `remove(at:)` para anular a necessidade de consultat a propriedade `count` do array. Assim como o método
Corrigir "consultat" para "consultar"

2022-03-31 17:31 UTC, reisdev commented on README.md
> +    - [x] Intro
Adicionar o link para as respectivas partes do arquivo traduzido

2022-03-31 23:59 UTC, GabrielaBezerra requested changes
Muito obrigada pela contribuição 🎉 o @reisdev fez um revisão muito boa desse PR (inclusive muito obrigada por isso também), agora é só fazer as alterações/correções que ele sugeriu, commitar, dar push, que a gente revisa de novo e faz o merge!

2022-04-01 00:13 UTC, TiagoSAmaral commented on LanguageGuide/CollectionTypes.md
>  var someInts = [Int]()
Fala ae! Obrigado pela review amigo. 
Em Convenções, não foi definido sobre isso.  Olhei outras partes já traduzidas, e parece haver a convenção (ou concordância) em conservar o código de exemplo no inglês. 

Com relação as demais mudanças, irei fazer ainda hoje! 

Obrigado mais uma vez!

2022-04-01 04:14 UTC, TiagoSAmaral commented
Fala galera! Ajustes e alterações solicitadas feitas! 
Obrigado pelo apoio!

2022-04-07 19:40 UTC, GabrielaBezerra approved these changes

2022-04-07 19:40 UTC, merged