Translate intro in the basics section
AcademyIFCE/swift-book-markdown pull request #44
Opened 2019-10-11 23:42 UTC by thatdaniboy

2019-10-12 03:28 UTC, trastoan commented on LanguageGuide/TheBasics.md
>  In addition to familiar types, Swift introduces advanced types not found in Objective-C, such as tuples. Tuples enable you to create and pass around groupings of values. You can use a tuple to return
Faltou deletar isso daqui

2019-10-12 03:29 UTC, trastoan requested changes

2019-10-12 03:29 UTC, trastoan commented on LanguageGuide/TheBasics.md
>  In addition to familiar types, Swift introduces advanced types not found in Objective-C, such as tuples. Tuples enable you to create and pass around groupings of values. You can use a tuple to return
Faltou deletar isso

2019-10-16 01:33 UTC, jessicalewinter commented
@thatdaniboy are you still going to translate this topic?

2019-10-25 16:42 UTC, mateusrodriguesxyz approved these changes

2019-10-28 20:35 UTC, trastoan approved these changes
Good to go

2019-10-28 20:35 UTC, merged