Finish closure-expressions
AcademyIFCE/swift-book-markdown pull request #75
Opened 2019-10-17 22:29 UTC by davicabral

2019-10-17 23:27 UTC, jessicalewinter requested changes
Lines requested to change

2019-10-17 23:27 UTC, jessicalewinter commented on LanguageGuide/Closures.md
> + *Closures* são blocos auto-contidos de código que podem ser passadas e utlizadas no seu código. *Closures* em Swift são similares a blocos em C/Objective-C e a *lambdas* em outras linguagem de progr
Change "utlizadas" to >> "utilizadas"

2019-10-17 23:27 UTC, jessicalewinter commented on LanguageGuide/Closures.md
> + *Global* e *Nested functions* , como introduzido em [Funções](Functions.md), são na realidade um tipo especial de closures. Closures assumem três formas:
Put *closures* in italic

2019-10-17 23:27 UTC, jessicalewinter commented on LanguageGuide/Closures.md
> +
Put *closures* in italic

2019-10-17 23:27 UTC, jessicalewinter commented on LanguageGuide/Closures.md
> + *   Inferir parametros e tipos de retorno do contexto
Change "parametros" to >> "parâmetros"

2019-10-17 23:27 UTC, jessicalewinter commented on LanguageGuide/Closures.md
> + *   Tipo de retorno implícito quando o corpo da closure possui apenas uma linha
Put *closures* in italic

2019-10-17 23:27 UTC, jessicalewinter commented on LanguageGuide/Closures.md
> +Expressões Closure
Put *closures* in italic

2019-10-17 23:27 UTC, jessicalewinter commented on LanguageGuide/Closures.md
> +*Nested functions*, como introduzido em [Nested Functions](Functions.md#nested-functions), é um modo conveniente de nomear e definir blocos auto-contidos de código como parte de uma função maior. Ent
Change "vc" to >> "você"

2019-10-17 23:27 UTC, jessicalewinter commented on LanguageGuide/Closures.md
> +*Expressões Closure* é uma maneira de escrever closures de modo enxuto e com sintaxe simples. *Expressões Closure* fornecem várias otimizações de sintaxe para a escrita de *closures*  de forma resumi
Put *closures* in italic

2019-10-17 23:27 UTC, jessicalewinter commented on LanguageGuide/Closures.md
> +A biblioteca padrão do Swift prover um método chamado `sorted(by:)`, o qual ordena os valores de um array baseado no retorno da closure de ordenação. Ao completar o processo de ordenação, o método `s
Put *array* in italic

2019-10-17 23:27 UTC, jessicalewinter commented on LanguageGuide/Closures.md
> +O exemplo abaixo usa o método `sorted(by:)` para ordenar um array de `String` na ordem contrária a alfabética. Este é o array inicial:
Put *array* in italic

2019-10-17 23:27 UTC, jessicalewinter commented on LanguageGuide/Closures.md
> +O método `sorted(by:)` recebe uma closure que possui dois argumentos do mesmo tipo do array e retorna um `Bool` que indica quando o primeiro valor deve ficar antes ou depois do segundo valor quando o
* Put *array* and *closure* in italic.
* Change "os *arrays* estiver reordenado" to >> "os *arrays* estiverem reordenados"

2019-10-17 23:27 UTC, jessicalewinter commented on LanguageGuide/Closures.md
> +Este exemplo esta ordenando um array de `String` então a closure de ordenação precisa ser uma função do tipo `(String, String) -> Bool`.
* Put *array* and *closure* in italic.
* Change "esta" to >> "está"

2019-10-17 23:27 UTC, jessicalewinter commented on LanguageGuide/Closures.md
> +Um dos modo de fornecer uma closure é escrevendo uma função normal do tipo esperado pelo parâmetro e então passar como argumento do método `sorted(by:)`:
* Put *closure* in italic.
* Change "dos modo" to >> "dos modos"

2019-10-17 23:27 UTC, jessicalewinter commented on LanguageGuide/Closures.md
> +// reversedNames é ["Ewa", "Daniella", "Chris", "Barry", "Alex"]
Change "é" to >> "é igual a"

2019-10-17 23:27 UTC, jessicalewinter commented on LanguageGuide/Closures.md
> +Se a primeira string (`s`) for maior que a segunda string (`s2`) a função `backward(_:_:)` irá retornar `true`, fazendo com que `s` fique antes de `s2` no array ordenado. Em relação a caracteres em u
Put *string* and *array* in italic.

2019-10-17 23:27 UTC, jessicalewinter commented on LanguageGuide/Closures.md
> +Entretanto, esta é um modo verboso de escrever uma simples expressão (`a > b`). Neste exemplo, seria mais adequado escrever uma expressão simplificada usando a sintaxe de Expressões Closure.
* Put *closure* in italic.
* Change "esta é" to >> "este é"

2019-10-17 23:27 UTC, jessicalewinter commented on LanguageGuide/Closures.md
> +Sintaxe de Expressões Closure possui a seguinte forma:
Put *closure* in italic.

2019-10-17 23:27 UTC, jessicalewinter commented on LanguageGuide/Closures.md
> +The *parameters* in closure expression syntax can be in-out parameters, but they can’t have a default value. Parâmetros *Variadic* podem ser utilizado caso vocês adicione um nome ao argumento. Tuplas
* Put *closure* in italic.
* Remove "The *parameters* in closure expression syntax can be in-out parameters, but they can’t have a default value."
* Put *Variadic* in low-case *variadic*
* Change "vocês" to "você"
* Change "parametros" to "parâmetros"

2019-10-17 23:27 UTC, jessicalewinter commented on LanguageGuide/Closures.md
> +O exemplo abaixo mostra uma expressão closure que implementa o mesmo que a função `backward(_:_:)`, mostrada acima:
Put *closure* in italic

2019-10-17 23:27 UTC, jessicalewinter commented on LanguageGuide/Closures.md
> +Perceba que a declaração dos parâmetros e tipo de returno para este tipo de closure é identica a declaração da função `backward(_:_:)`. Em ambos os casos, foi escrito como `(s: String, s2: String) ->
* Change "returno" to >> "retorno"
* Change "identica" to >> "idêntica"
* Put *closure* in italic

2019-10-17 23:27 UTC, jessicalewinter commented on LanguageGuide/Closures.md
> +O início do corpo da closure é iniciado pela palavra reservada `in`. Esta palavra reservada indica que a definição dos parametros e retorno da closure terminaram, e o que o corpo da closure esta pres
* Put *closure* in italic
* Change "parametros" to "parâmetros"

2019-10-17 23:27 UTC, jessicalewinter commented on LanguageGuide/Closures.md
> +Como o corpo da closure é pequeno, é possível até escrever ele em uma única linha:
* Put *closure* in italic

2019-10-17 23:27 UTC, jessicalewinter commented on LanguageGuide/Closures.md
> +Isto ilustra  que a chamada do método `sorted(by:)` continua a mesma. Um par de parênteses continua envolvendo todos os argumentos do método. Porém, este argumento agora é uma closure.
* Put *closure* in italic

2019-10-17 23:27 UTC, jessicalewinter commented on LanguageGuide/Closures.md
> +Em razão da closure ser passada como um argumento para o método, o Swift pode inferir os tipos de seus parâmetros e retorno. O método `sorted(by:)` é chamado de um array de strings, então o argumento
* Put *array*, *string*, *closure* in italic
* Change "parametros" to "parâmetros"
* Change "parenteses" to "parênteses"
* Change "pode ser omitido" to "podem ser omitidos"

2019-10-17 23:27 UTC, jessicalewinter commented on LanguageGuide/Closures.md
> +É sempre possível inferir os tipos dos parametros e do retorno quando passamos uma closure para uma função ou método. Por conta disto você nunca precisa escrever uma closure diretamente na função na
* Put *closure* in italic
* Change "parametros" to "parâmetros"

2019-10-17 23:27 UTC, jessicalewinter commented on LanguageGuide/Closures.md
> +No entanto, você ainda pode explicitar os tipos se você quiser, e é interessante fazê-lo se isto evitar ambiguidade para os leitores do código. No caso da closure do método `sorted(by:)` é claro que
* Put *array*, *closure* in italic
* Change "parametros" to "parâmetros"
* Change "se isto evitar" to "se isto for evitar"

2019-10-17 23:27 UTC, jessicalewinter commented on LanguageGuide/Closures.md
> +### Return Implícito de Closures de Única Linha
* Put *closure* in italic
* Change "return" to "retorno"

2019-10-17 23:27 UTC, jessicalewinter commented on LanguageGuide/Closures.md
> +Closures de Única Linha retorna o resultado da instrução omitingo a palavra reservada `return` na declaração, como está no exemplo abaixo:
* Put *closure* in italic
* Change "omitingo" to "omitindo"

2019-10-17 23:27 UTC, jessicalewinter commented on LanguageGuide/Closures.md
> +Neste exemplo o tipo do parametro do método `sorted(by:)` deixa claro que o tipo do retorno é `Bool`. Como o corpo da closure contém apenas uma expressão (`s > s2`) que já retorna um valor do tipo `B
* Put *closure* in italic
* Change "parametro" to "parâmetro"

2019-10-17 23:27 UTC, jessicalewinter commented on LanguageGuide/Closures.md
> +### Argumentos com nomes suprimidos
Change "suprimidos" to "abreviados"

2019-10-17 23:27 UTC, jessicalewinter commented on LanguageGuide/Closures.md
> +O Swift automaticamente fornece argumentos com nomes suprimidos para closures escritas diretamente, neste caso é possível acessar os valores dos parâmetros da closures utilizando nomes `$0`, `$1`, `$
* Change "suprimidos" to "abreviados"
* Put closure in italic

2019-10-17 23:27 UTC, jessicalewinter commented on LanguageGuide/Closures.md
> +Se você utilizar este tipo de nomenclatura de argumentos na sua closure, você pode omitir a lista de parâmetros durante a sua implementação, assim o número e tipo do argumento será inferido de acordo
* Put *closure* in italic

2019-10-17 23:27 UTC, jessicalewinter commented on LanguageGuide/Closures.md
> +Há ainda uma maneira mais enxuta de escrever o mesmo exemplo acima. Em Swift o tipo `String` define a implementação do operador Maior Que (`>`) como um método que tem dois parametros do tipo `String`
* Put *closure* in italic
* Put comma after "Por conta disto"
* Change  "você pode simplesmente passa o operador" to >> " "você pode simplesmente passar o operador"

2019-10-18 00:27 UTC, davicabral commented on LanguageGuide/Closures.md
> + *Global* e *Nested functions* , como introduzido em [Funções](Functions.md), são na realidade um tipo especial de closures. Closures assumem três formas:
All closures or just the uppercased?

2019-10-18 00:32 UTC, davicabral commented
Should I use italic everytime I translate closure?

2019-10-18 09:42 UTC, jessicalewinter commented on LanguageGuide/Closures.md
> + *Global* e *Nested functions* , como introduzido em [Funções](Functions.md), são na realidade um tipo especial de closures. Closures assumem três formas:
all closures should be in italic

2019-10-18 09:43 UTC, jessicalewinter commented
> Should I use italic everytime I translate closure?

Yes, I think so.

2019-10-20 14:04 UTC, mateusrodriguesxyz approved these changes

2019-10-21 12:46 UTC, jessicalewinter approved these changes
Ok,changes done

2019-10-21 12:46 UTC, merged